<?php
/**
 * MedicationIngredient
 *
 * PHP version 5
 *
 * @category Class
 * @package  Mediator\SatuSehat\Lib\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Swagger Mediator  SATUSEHAT
 *
 * Spesifikasi API ini merupakan contoh untuk menggunakan **Mediator Interoperabilitas SATUSEHAT** yang secara khusus ditujukan untuk mempercepat dan memudahkan proses interoperabilitas data Rekam Medis Elektronik (RME) antara sistem informasi di Fasilitas Kesehatan (Rumah Sakit, Puskesmas, Klinik, Laboratorium, dll) dengan Platform SATUSEHAT.  Mediator Interoperabilitas SATUSEHAT menyediakan format custom yang disederhanakan dari format HL7 FHIR sebagai perantara antara sistem RME dengan SATUSEHAT beserta sistem informasi kesehatan yang ada ditingkat nasional.
 *
 * OpenAPI spec version: 1.0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.59
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Mediator\SatuSehat\Lib\Client\Model;

use ArrayAccess;
use Mediator\SatuSehat\Lib\Client\ObjectSerializer;

/**
 * MedicationIngredient Class Doc Comment
 *
 * @category Class
 * @package  Mediator\SatuSehat\Lib\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MedicationIngredient implements ModelInterface, ArrayAccess
{
    public static $DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'MedicationIngredient';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'kfa_code' => 'string',
        'kfa_display' => 'string',
        'numerator_value' => 'int',
        'numerator_unit' => 'string',
        'denominator_value' => 'int',
        'denominator_unit' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'kfa_code' => null,
        'kfa_display' => null,
        'numerator_value' => null,
        'numerator_unit' => null,
        'denominator_value' => null,
        'denominator_unit' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'kfa_code' => 'kfa_code',
        'kfa_display' => 'kfa_display',
        'numerator_value' => 'numerator_value',
        'numerator_unit' => 'numerator_unit',
        'denominator_value' => 'denominator_value',
        'denominator_unit' => 'denominator_unit'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'kfa_code' => 'setKfaCode',
        'kfa_display' => 'setKfaDisplay',
        'numerator_value' => 'setNumeratorValue',
        'numerator_unit' => 'setNumeratorUnit',
        'denominator_value' => 'setDenominatorValue',
        'denominator_unit' => 'setDenominatorUnit'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'kfa_code' => 'getKfaCode',
        'kfa_display' => 'getKfaDisplay',
        'numerator_value' => 'getNumeratorValue',
        'numerator_unit' => 'getNumeratorUnit',
        'denominator_value' => 'getDenominatorValue',
        'denominator_unit' => 'getDenominatorUnit'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['kfa_code'] = isset($data['kfa_code']) ? $data['kfa_code'] : null;
        $this->container['kfa_display'] = isset($data['kfa_display']) ? $data['kfa_display'] : null;
        $this->container['numerator_value'] = isset($data['numerator_value']) ? $data['numerator_value'] : null;
        $this->container['numerator_unit'] = isset($data['numerator_unit']) ? $data['numerator_unit'] : null;
        $this->container['denominator_value'] = isset($data['denominator_value']) ? $data['denominator_value'] : null;
        $this->container['denominator_unit'] = isset($data['denominator_unit']) ? $data['denominator_unit'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets kfa_code
     *
     * @return string
     */
    public function getKfaCode()
    {
        return $this->container['kfa_code'];
    }

    /**
     * Sets kfa_code
     *
     * @param string $kfa_code kfa_code
     *
     * @return $this
     */
    public function setKfaCode($kfa_code)
    {
        $this->container['kfa_code'] = $kfa_code;

        return $this;
    }

    /**
     * Gets kfa_display
     *
     * @return string
     */
    public function getKfaDisplay()
    {
        return $this->container['kfa_display'];
    }

    /**
     * Sets kfa_display
     *
     * @param string $kfa_display kfa_display
     *
     * @return $this
     */
    public function setKfaDisplay($kfa_display)
    {
        $this->container['kfa_display'] = $kfa_display;

        return $this;
    }

    /**
     * Gets numerator_value
     *
     * @return int
     */
    public function getNumeratorValue()
    {
        return $this->container['numerator_value'];
    }

    /**
     * Sets numerator_value
     *
     * @param int $numerator_value numerator_value
     *
     * @return $this
     */
    public function setNumeratorValue($numerator_value)
    {
        $this->container['numerator_value'] = $numerator_value;

        return $this;
    }

    /**
     * Gets numerator_unit
     *
     * @return string
     */
    public function getNumeratorUnit()
    {
        return $this->container['numerator_unit'];
    }

    /**
     * Sets numerator_unit
     *
     * @param string $numerator_unit numerator_unit
     *
     * @return $this
     */
    public function setNumeratorUnit($numerator_unit)
    {
        $this->container['numerator_unit'] = $numerator_unit;

        return $this;
    }

    /**
     * Gets denominator_value
     *
     * @return int
     */
    public function getDenominatorValue()
    {
        return $this->container['denominator_value'];
    }

    /**
     * Sets denominator_value
     *
     * @param int $denominator_value denominator_value
     *
     * @return $this
     */
    public function setDenominatorValue($denominator_value)
    {
        $this->container['denominator_value'] = $denominator_value;

        return $this;
    }

    /**
     * Gets denominator_unit
     *
     * @return string
     */
    public function getDenominatorUnit()
    {
        return $this->container['denominator_unit'];
    }

    /**
     * Sets denominator_unit
     *
     * @param string $denominator_unit denominator_unit
     *
     * @return $this
     */
    public function setDenominatorUnit($denominator_unit)
    {
        $this->container['denominator_unit'] = $denominator_unit;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
