<?php
/**
 * TbSuspect
 *
 * PHP version 5
 *
 * @category Class
 * @package  Mediator\SatuSehat\Lib\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Swagger Mediator  SATUSEHAT
 *
 * Spesifikasi API ini merupakan contoh untuk menggunakan **Mediator Interoperabilitas SATUSEHAT** yang secara khusus ditujukan untuk mempercepat dan memudahkan proses interoperabilitas data Rekam Medis Elektronik (RME) antara sistem informasi di Fasilitas Kesehatan (Rumah Sakit, Puskesmas, Klinik, Laboratorium, dll) dengan Platform SATUSEHAT.  Mediator Interoperabilitas SATUSEHAT menyediakan format custom yang disederhanakan dari format HL7 FHIR sebagai perantara antara sistem RME dengan SATUSEHAT beserta sistem informasi kesehatan yang ada ditingkat nasional.
 *
 * OpenAPI spec version: 1.0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.59
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Mediator\SatuSehat\Lib\Client\Model;

use Mediator\SatuSehat\Lib\Client\ObjectSerializer;

/**
 * TbSuspect Class Doc Comment
 *
 * @category Class
 * @package  Mediator\SatuSehat\Lib\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TbSuspect extends MediatorResourceBasic
{
    public static $DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'TbSuspect';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'string',
        'person_id' => 'string',
        'tgl_daftar' => '\DateTime',
        'fasyankes_id' => 'string',
        'jenis_fasyankes_id' => 'string',
        'fasyankes_provinsi_id' => 'string',
        'fasyankes_kabupaten_id' => 'string',
        'umur' => 'int',
        'umur_bl' => 'int',
        'fasyankes_rujukan_id' => 'string',
        'jenis_fasyankes_rujukan_id' => 'string',
        'fasyankes_rujukan_lain' => 'string',
        'provinsi_rujukan_id' => 'string',
        'kabupaten_rujukan_id' => 'string',
        'asal_rujukan_id' => 'string',
        'asal_rujukan_lain' => 'string',
        'fasyankes_rujukan_asal_id' => 'string',
        'terduga_tb_id' => 'string',
        'terduga_ro_id' => 'string',
        'tipe_pasien_id' => 'string',
        'skoring_tbc_anak' => 'string',
        'status_dm_id' => 'string',
        'status_hiv_id' => 'string',
        'imunisasi_bcg_id' => 'string',
        'no_reg_fasyankes' => 'string',
        'reg_kab_id' => 'string',
        'no_reg_kab' => 'string',
        'location_anatomy' => 'string',
        'confirm_id' => 'string',
        'lab_id' => 'string',
        'specimen_id' => 'string',
        'no_sediaan' => 'string',
        'no_urut' => 'string',
        'error' => 'string',
        'success' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => null,
        'person_id' => null,
        'tgl_daftar' => 'date',
        'fasyankes_id' => null,
        'jenis_fasyankes_id' => null,
        'fasyankes_provinsi_id' => null,
        'fasyankes_kabupaten_id' => null,
        'umur' => null,
        'umur_bl' => null,
        'fasyankes_rujukan_id' => null,
        'jenis_fasyankes_rujukan_id' => null,
        'fasyankes_rujukan_lain' => null,
        'provinsi_rujukan_id' => null,
        'kabupaten_rujukan_id' => null,
        'asal_rujukan_id' => null,
        'asal_rujukan_lain' => null,
        'fasyankes_rujukan_asal_id' => null,
        'terduga_tb_id' => null,
        'terduga_ro_id' => null,
        'tipe_pasien_id' => null,
        'skoring_tbc_anak' => null,
        'status_dm_id' => null,
        'status_hiv_id' => null,
        'imunisasi_bcg_id' => null,
        'no_reg_fasyankes' => null,
        'reg_kab_id' => null,
        'no_reg_kab' => null,
        'location_anatomy' => null,
        'confirm_id' => null,
        'lab_id' => null,
        'specimen_id' => null,
        'no_sediaan' => null,
        'no_urut' => null,
        'error' => null,
        'success' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes + parent::swaggerTypes();
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats + parent::swaggerFormats();
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'person_id' => 'person_id',
        'tgl_daftar' => 'tgl_daftar',
        'fasyankes_id' => 'fasyankes_id',
        'jenis_fasyankes_id' => 'jenis_fasyankes_id',
        'fasyankes_provinsi_id' => 'fasyankes_provinsi_id',
        'fasyankes_kabupaten_id' => 'fasyankes_kabupaten_id',
        'umur' => 'umur',
        'umur_bl' => 'umur_bl',
        'fasyankes_rujukan_id' => 'fasyankes_rujukan_id',
        'jenis_fasyankes_rujukan_id' => 'jenis_fasyankes_rujukan_id',
        'fasyankes_rujukan_lain' => 'fasyankes_rujukan_lain',
        'provinsi_rujukan_id' => 'provinsi_rujukan_id',
        'kabupaten_rujukan_id' => 'kabupaten_rujukan_id',
        'asal_rujukan_id' => 'asal_rujukan_id',
        'asal_rujukan_lain' => 'asal_rujukan_lain',
        'fasyankes_rujukan_asal_id' => 'fasyankes_rujukan_asal_id',
        'terduga_tb_id' => 'terduga_tb_id',
        'terduga_ro_id' => 'terduga_ro_id',
        'tipe_pasien_id' => 'tipe_pasien_id',
        'skoring_tbc_anak' => 'skoring_tbc_anak',
        'status_dm_id' => 'status_dm_id',
        'status_hiv_id' => 'status_hiv_id',
        'imunisasi_bcg_id' => 'imunisasi_bcg_id',
        'no_reg_fasyankes' => 'no_reg_fasyankes',
        'reg_kab_id' => 'reg_kab_id',
        'no_reg_kab' => 'no_reg_kab',
        'location_anatomy' => 'location_anatomy',
        'confirm_id' => 'confirm_id',
        'lab_id' => 'lab_id',
        'specimen_id' => 'specimen_id',
        'no_sediaan' => 'no_sediaan',
        'no_urut' => 'no_urut',
        'error' => 'error',
        'success' => 'success'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'person_id' => 'setPersonId',
        'tgl_daftar' => 'setTglDaftar',
        'fasyankes_id' => 'setFasyankesId',
        'jenis_fasyankes_id' => 'setJenisFasyankesId',
        'fasyankes_provinsi_id' => 'setFasyankesProvinsiId',
        'fasyankes_kabupaten_id' => 'setFasyankesKabupatenId',
        'umur' => 'setUmur',
        'umur_bl' => 'setUmurBl',
        'fasyankes_rujukan_id' => 'setFasyankesRujukanId',
        'jenis_fasyankes_rujukan_id' => 'setJenisFasyankesRujukanId',
        'fasyankes_rujukan_lain' => 'setFasyankesRujukanLain',
        'provinsi_rujukan_id' => 'setProvinsiRujukanId',
        'kabupaten_rujukan_id' => 'setKabupatenRujukanId',
        'asal_rujukan_id' => 'setAsalRujukanId',
        'asal_rujukan_lain' => 'setAsalRujukanLain',
        'fasyankes_rujukan_asal_id' => 'setFasyankesRujukanAsalId',
        'terduga_tb_id' => 'setTerdugaTbId',
        'terduga_ro_id' => 'setTerdugaRoId',
        'tipe_pasien_id' => 'setTipePasienId',
        'skoring_tbc_anak' => 'setSkoringTbcAnak',
        'status_dm_id' => 'setStatusDmId',
        'status_hiv_id' => 'setStatusHivId',
        'imunisasi_bcg_id' => 'setImunisasiBcgId',
        'no_reg_fasyankes' => 'setNoRegFasyankes',
        'reg_kab_id' => 'setRegKabId',
        'no_reg_kab' => 'setNoRegKab',
        'location_anatomy' => 'setLocationAnatomy',
        'confirm_id' => 'setConfirmId',
        'lab_id' => 'setLabId',
        'specimen_id' => 'setSpecimenId',
        'no_sediaan' => 'setNoSediaan',
        'no_urut' => 'setNoUrut',
        'error' => 'setError',
        'success' => 'setSuccess'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'person_id' => 'getPersonId',
        'tgl_daftar' => 'getTglDaftar',
        'fasyankes_id' => 'getFasyankesId',
        'jenis_fasyankes_id' => 'getJenisFasyankesId',
        'fasyankes_provinsi_id' => 'getFasyankesProvinsiId',
        'fasyankes_kabupaten_id' => 'getFasyankesKabupatenId',
        'umur' => 'getUmur',
        'umur_bl' => 'getUmurBl',
        'fasyankes_rujukan_id' => 'getFasyankesRujukanId',
        'jenis_fasyankes_rujukan_id' => 'getJenisFasyankesRujukanId',
        'fasyankes_rujukan_lain' => 'getFasyankesRujukanLain',
        'provinsi_rujukan_id' => 'getProvinsiRujukanId',
        'kabupaten_rujukan_id' => 'getKabupatenRujukanId',
        'asal_rujukan_id' => 'getAsalRujukanId',
        'asal_rujukan_lain' => 'getAsalRujukanLain',
        'fasyankes_rujukan_asal_id' => 'getFasyankesRujukanAsalId',
        'terduga_tb_id' => 'getTerdugaTbId',
        'terduga_ro_id' => 'getTerdugaRoId',
        'tipe_pasien_id' => 'getTipePasienId',
        'skoring_tbc_anak' => 'getSkoringTbcAnak',
        'status_dm_id' => 'getStatusDmId',
        'status_hiv_id' => 'getStatusHivId',
        'imunisasi_bcg_id' => 'getImunisasiBcgId',
        'no_reg_fasyankes' => 'getNoRegFasyankes',
        'reg_kab_id' => 'getRegKabId',
        'no_reg_kab' => 'getNoRegKab',
        'location_anatomy' => 'getLocationAnatomy',
        'confirm_id' => 'getConfirmId',
        'lab_id' => 'getLabId',
        'specimen_id' => 'getSpecimenId',
        'no_sediaan' => 'getNoSediaan',
        'no_urut' => 'getNoUrut',
        'error' => 'getError',
        'success' => 'getSuccess'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return parent::attributeMap() + self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return parent::setters() + self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return parent::getters() + self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        parent::__construct($data);

        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['person_id'] = isset($data['person_id']) ? $data['person_id'] : null;
        $this->container['tgl_daftar'] = isset($data['tgl_daftar']) ? $data['tgl_daftar'] : null;
        $this->container['fasyankes_id'] = isset($data['fasyankes_id']) ? $data['fasyankes_id'] : null;
        $this->container['jenis_fasyankes_id'] = isset($data['jenis_fasyankes_id']) ? $data['jenis_fasyankes_id'] : null;
        $this->container['fasyankes_provinsi_id'] = isset($data['fasyankes_provinsi_id']) ? $data['fasyankes_provinsi_id'] : null;
        $this->container['fasyankes_kabupaten_id'] = isset($data['fasyankes_kabupaten_id']) ? $data['fasyankes_kabupaten_id'] : null;
        $this->container['umur'] = isset($data['umur']) ? $data['umur'] : null;
        $this->container['umur_bl'] = isset($data['umur_bl']) ? $data['umur_bl'] : null;
        $this->container['fasyankes_rujukan_id'] = isset($data['fasyankes_rujukan_id']) ? $data['fasyankes_rujukan_id'] : null;
        $this->container['jenis_fasyankes_rujukan_id'] = isset($data['jenis_fasyankes_rujukan_id']) ? $data['jenis_fasyankes_rujukan_id'] : null;
        $this->container['fasyankes_rujukan_lain'] = isset($data['fasyankes_rujukan_lain']) ? $data['fasyankes_rujukan_lain'] : null;
        $this->container['provinsi_rujukan_id'] = isset($data['provinsi_rujukan_id']) ? $data['provinsi_rujukan_id'] : null;
        $this->container['kabupaten_rujukan_id'] = isset($data['kabupaten_rujukan_id']) ? $data['kabupaten_rujukan_id'] : null;
        $this->container['asal_rujukan_id'] = isset($data['asal_rujukan_id']) ? $data['asal_rujukan_id'] : null;
        $this->container['asal_rujukan_lain'] = isset($data['asal_rujukan_lain']) ? $data['asal_rujukan_lain'] : null;
        $this->container['fasyankes_rujukan_asal_id'] = isset($data['fasyankes_rujukan_asal_id']) ? $data['fasyankes_rujukan_asal_id'] : null;
        $this->container['terduga_tb_id'] = isset($data['terduga_tb_id']) ? $data['terduga_tb_id'] : null;
        $this->container['terduga_ro_id'] = isset($data['terduga_ro_id']) ? $data['terduga_ro_id'] : null;
        $this->container['tipe_pasien_id'] = isset($data['tipe_pasien_id']) ? $data['tipe_pasien_id'] : null;
        $this->container['skoring_tbc_anak'] = isset($data['skoring_tbc_anak']) ? $data['skoring_tbc_anak'] : null;
        $this->container['status_dm_id'] = isset($data['status_dm_id']) ? $data['status_dm_id'] : null;
        $this->container['status_hiv_id'] = isset($data['status_hiv_id']) ? $data['status_hiv_id'] : null;
        $this->container['imunisasi_bcg_id'] = isset($data['imunisasi_bcg_id']) ? $data['imunisasi_bcg_id'] : null;
        $this->container['no_reg_fasyankes'] = isset($data['no_reg_fasyankes']) ? $data['no_reg_fasyankes'] : null;
        $this->container['reg_kab_id'] = isset($data['reg_kab_id']) ? $data['reg_kab_id'] : null;
        $this->container['no_reg_kab'] = isset($data['no_reg_kab']) ? $data['no_reg_kab'] : null;
        $this->container['location_anatomy'] = isset($data['location_anatomy']) ? $data['location_anatomy'] : null;
        $this->container['confirm_id'] = isset($data['confirm_id']) ? $data['confirm_id'] : null;
        $this->container['lab_id'] = isset($data['lab_id']) ? $data['lab_id'] : null;
        $this->container['specimen_id'] = isset($data['specimen_id']) ? $data['specimen_id'] : null;
        $this->container['no_sediaan'] = isset($data['no_sediaan']) ? $data['no_sediaan'] : null;
        $this->container['no_urut'] = isset($data['no_urut']) ? $data['no_urut'] : null;
        $this->container['error'] = isset($data['error']) ? $data['error'] : null;
        $this->container['success'] = isset($data['success']) ? $data['success'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets person_id
     *
     * @return string
     */
    public function getPersonId()
    {
        return $this->container['person_id'];
    }

    /**
     * Sets person_id
     *
     * @param string $person_id person_id
     *
     * @return $this
     */
    public function setPersonId($person_id)
    {
        $this->container['person_id'] = $person_id;

        return $this;
    }

    /**
     * Gets tgl_daftar
     *
     * @return \DateTime
     */
    public function getTglDaftar()
    {
        return $this->container['tgl_daftar'];
    }

    /**
     * Sets tgl_daftar
     *
     * @param \DateTime $tgl_daftar tgl_daftar
     *
     * @return $this
     */
    public function setTglDaftar($tgl_daftar)
    {
        $this->container['tgl_daftar'] = $tgl_daftar;

        return $this;
    }

    /**
     * Gets fasyankes_id
     *
     * @return string
     */
    public function getFasyankesId()
    {
        return $this->container['fasyankes_id'];
    }

    /**
     * Sets fasyankes_id
     *
     * @param string $fasyankes_id fasyankes_id
     *
     * @return $this
     */
    public function setFasyankesId($fasyankes_id)
    {
        $this->container['fasyankes_id'] = $fasyankes_id;

        return $this;
    }

    /**
     * Gets jenis_fasyankes_id
     *
     * @return string
     */
    public function getJenisFasyankesId()
    {
        return $this->container['jenis_fasyankes_id'];
    }

    /**
     * Sets jenis_fasyankes_id
     *
     * @param string $jenis_fasyankes_id jenis_fasyankes_id
     *
     * @return $this
     */
    public function setJenisFasyankesId($jenis_fasyankes_id)
    {
        $this->container['jenis_fasyankes_id'] = $jenis_fasyankes_id;

        return $this;
    }

    /**
     * Gets fasyankes_provinsi_id
     *
     * @return string
     */
    public function getFasyankesProvinsiId()
    {
        return $this->container['fasyankes_provinsi_id'];
    }

    /**
     * Sets fasyankes_provinsi_id
     *
     * @param string $fasyankes_provinsi_id fasyankes_provinsi_id
     *
     * @return $this
     */
    public function setFasyankesProvinsiId($fasyankes_provinsi_id)
    {
        $this->container['fasyankes_provinsi_id'] = $fasyankes_provinsi_id;

        return $this;
    }

    /**
     * Gets fasyankes_kabupaten_id
     *
     * @return string
     */
    public function getFasyankesKabupatenId()
    {
        return $this->container['fasyankes_kabupaten_id'];
    }

    /**
     * Sets fasyankes_kabupaten_id
     *
     * @param string $fasyankes_kabupaten_id fasyankes_kabupaten_id
     *
     * @return $this
     */
    public function setFasyankesKabupatenId($fasyankes_kabupaten_id)
    {
        $this->container['fasyankes_kabupaten_id'] = $fasyankes_kabupaten_id;

        return $this;
    }

    /**
     * Gets umur
     *
     * @return int
     */
    public function getUmur()
    {
        return $this->container['umur'];
    }

    /**
     * Sets umur
     *
     * @param int $umur umur
     *
     * @return $this
     */
    public function setUmur($umur)
    {
        $this->container['umur'] = $umur;

        return $this;
    }

    /**
     * Gets umur_bl
     *
     * @return int
     */
    public function getUmurBl()
    {
        return $this->container['umur_bl'];
    }

    /**
     * Sets umur_bl
     *
     * @param int $umur_bl umur_bl
     *
     * @return $this
     */
    public function setUmurBl($umur_bl)
    {
        $this->container['umur_bl'] = $umur_bl;

        return $this;
    }

    /**
     * Gets fasyankes_rujukan_id
     *
     * @return string
     */
    public function getFasyankesRujukanId()
    {
        return $this->container['fasyankes_rujukan_id'];
    }

    /**
     * Sets fasyankes_rujukan_id
     *
     * @param string $fasyankes_rujukan_id fasyankes_rujukan_id
     *
     * @return $this
     */
    public function setFasyankesRujukanId($fasyankes_rujukan_id)
    {
        $this->container['fasyankes_rujukan_id'] = $fasyankes_rujukan_id;

        return $this;
    }

    /**
     * Gets jenis_fasyankes_rujukan_id
     *
     * @return string
     */
    public function getJenisFasyankesRujukanId()
    {
        return $this->container['jenis_fasyankes_rujukan_id'];
    }

    /**
     * Sets jenis_fasyankes_rujukan_id
     *
     * @param string $jenis_fasyankes_rujukan_id jenis_fasyankes_rujukan_id
     *
     * @return $this
     */
    public function setJenisFasyankesRujukanId($jenis_fasyankes_rujukan_id)
    {
        $this->container['jenis_fasyankes_rujukan_id'] = $jenis_fasyankes_rujukan_id;

        return $this;
    }

    /**
     * Gets fasyankes_rujukan_lain
     *
     * @return string
     */
    public function getFasyankesRujukanLain()
    {
        return $this->container['fasyankes_rujukan_lain'];
    }

    /**
     * Sets fasyankes_rujukan_lain
     *
     * @param string $fasyankes_rujukan_lain fasyankes_rujukan_lain
     *
     * @return $this
     */
    public function setFasyankesRujukanLain($fasyankes_rujukan_lain)
    {
        $this->container['fasyankes_rujukan_lain'] = $fasyankes_rujukan_lain;

        return $this;
    }

    /**
     * Gets provinsi_rujukan_id
     *
     * @return string
     */
    public function getProvinsiRujukanId()
    {
        return $this->container['provinsi_rujukan_id'];
    }

    /**
     * Sets provinsi_rujukan_id
     *
     * @param string $provinsi_rujukan_id provinsi_rujukan_id
     *
     * @return $this
     */
    public function setProvinsiRujukanId($provinsi_rujukan_id)
    {
        $this->container['provinsi_rujukan_id'] = $provinsi_rujukan_id;

        return $this;
    }

    /**
     * Gets kabupaten_rujukan_id
     *
     * @return string
     */
    public function getKabupatenRujukanId()
    {
        return $this->container['kabupaten_rujukan_id'];
    }

    /**
     * Sets kabupaten_rujukan_id
     *
     * @param string $kabupaten_rujukan_id kabupaten_rujukan_id
     *
     * @return $this
     */
    public function setKabupatenRujukanId($kabupaten_rujukan_id)
    {
        $this->container['kabupaten_rujukan_id'] = $kabupaten_rujukan_id;

        return $this;
    }

    /**
     * Gets asal_rujukan_id
     *
     * @return string
     */
    public function getAsalRujukanId()
    {
        return $this->container['asal_rujukan_id'];
    }

    /**
     * Sets asal_rujukan_id
     *
     * @param string $asal_rujukan_id asal_rujukan_id
     *
     * @return $this
     */
    public function setAsalRujukanId($asal_rujukan_id)
    {
        $this->container['asal_rujukan_id'] = $asal_rujukan_id;

        return $this;
    }

    /**
     * Gets asal_rujukan_lain
     *
     * @return string
     */
    public function getAsalRujukanLain()
    {
        return $this->container['asal_rujukan_lain'];
    }

    /**
     * Sets asal_rujukan_lain
     *
     * @param string $asal_rujukan_lain asal_rujukan_lain
     *
     * @return $this
     */
    public function setAsalRujukanLain($asal_rujukan_lain)
    {
        $this->container['asal_rujukan_lain'] = $asal_rujukan_lain;

        return $this;
    }

    /**
     * Gets fasyankes_rujukan_asal_id
     *
     * @return string
     */
    public function getFasyankesRujukanAsalId()
    {
        return $this->container['fasyankes_rujukan_asal_id'];
    }

    /**
     * Sets fasyankes_rujukan_asal_id
     *
     * @param string $fasyankes_rujukan_asal_id fasyankes_rujukan_asal_id
     *
     * @return $this
     */
    public function setFasyankesRujukanAsalId($fasyankes_rujukan_asal_id)
    {
        $this->container['fasyankes_rujukan_asal_id'] = $fasyankes_rujukan_asal_id;

        return $this;
    }

    /**
     * Gets terduga_tb_id
     *
     * @return string
     */
    public function getTerdugaTbId()
    {
        return $this->container['terduga_tb_id'];
    }

    /**
     * Sets terduga_tb_id
     *
     * @param string $terduga_tb_id terduga_tb_id
     *
     * @return $this
     */
    public function setTerdugaTbId($terduga_tb_id)
    {
        $this->container['terduga_tb_id'] = $terduga_tb_id;

        return $this;
    }

    /**
     * Gets terduga_ro_id
     *
     * @return string
     */
    public function getTerdugaRoId()
    {
        return $this->container['terduga_ro_id'];
    }

    /**
     * Sets terduga_ro_id
     *
     * @param string $terduga_ro_id terduga_ro_id
     *
     * @return $this
     */
    public function setTerdugaRoId($terduga_ro_id)
    {
        $this->container['terduga_ro_id'] = $terduga_ro_id;

        return $this;
    }

    /**
     * Gets tipe_pasien_id
     *
     * @return string
     */
    public function getTipePasienId()
    {
        return $this->container['tipe_pasien_id'];
    }

    /**
     * Sets tipe_pasien_id
     *
     * @param string $tipe_pasien_id tipe_pasien_id
     *
     * @return $this
     */
    public function setTipePasienId($tipe_pasien_id)
    {
        $this->container['tipe_pasien_id'] = $tipe_pasien_id;

        return $this;
    }

    /**
     * Gets skoring_tbc_anak
     *
     * @return string
     */
    public function getSkoringTbcAnak()
    {
        return $this->container['skoring_tbc_anak'];
    }

    /**
     * Sets skoring_tbc_anak
     *
     * @param string $skoring_tbc_anak skoring_tbc_anak
     *
     * @return $this
     */
    public function setSkoringTbcAnak($skoring_tbc_anak)
    {
        $this->container['skoring_tbc_anak'] = $skoring_tbc_anak;

        return $this;
    }

    /**
     * Gets status_dm_id
     *
     * @return string
     */
    public function getStatusDmId()
    {
        return $this->container['status_dm_id'];
    }

    /**
     * Sets status_dm_id
     *
     * @param string $status_dm_id status_dm_id
     *
     * @return $this
     */
    public function setStatusDmId($status_dm_id)
    {
        $this->container['status_dm_id'] = $status_dm_id;

        return $this;
    }

    /**
     * Gets status_hiv_id
     *
     * @return string
     */
    public function getStatusHivId()
    {
        return $this->container['status_hiv_id'];
    }

    /**
     * Sets status_hiv_id
     *
     * @param string $status_hiv_id status_hiv_id
     *
     * @return $this
     */
    public function setStatusHivId($status_hiv_id)
    {
        $this->container['status_hiv_id'] = $status_hiv_id;

        return $this;
    }

    /**
     * Gets imunisasi_bcg_id
     *
     * @return string
     */
    public function getImunisasiBcgId()
    {
        return $this->container['imunisasi_bcg_id'];
    }

    /**
     * Sets imunisasi_bcg_id
     *
     * @param string $imunisasi_bcg_id imunisasi_bcg_id
     *
     * @return $this
     */
    public function setImunisasiBcgId($imunisasi_bcg_id)
    {
        $this->container['imunisasi_bcg_id'] = $imunisasi_bcg_id;

        return $this;
    }

    /**
     * Gets no_reg_fasyankes
     *
     * @return string
     */
    public function getNoRegFasyankes()
    {
        return $this->container['no_reg_fasyankes'];
    }

    /**
     * Sets no_reg_fasyankes
     *
     * @param string $no_reg_fasyankes no_reg_fasyankes
     *
     * @return $this
     */
    public function setNoRegFasyankes($no_reg_fasyankes)
    {
        $this->container['no_reg_fasyankes'] = $no_reg_fasyankes;

        return $this;
    }

    /**
     * Gets reg_kab_id
     *
     * @return string
     */
    public function getRegKabId()
    {
        return $this->container['reg_kab_id'];
    }

    /**
     * Sets reg_kab_id
     *
     * @param string $reg_kab_id reg_kab_id
     *
     * @return $this
     */
    public function setRegKabId($reg_kab_id)
    {
        $this->container['reg_kab_id'] = $reg_kab_id;

        return $this;
    }

    /**
     * Gets no_reg_kab
     *
     * @return string
     */
    public function getNoRegKab()
    {
        return $this->container['no_reg_kab'];
    }

    /**
     * Sets no_reg_kab
     *
     * @param string $no_reg_kab no_reg_kab
     *
     * @return $this
     */
    public function setNoRegKab($no_reg_kab)
    {
        $this->container['no_reg_kab'] = $no_reg_kab;

        return $this;
    }

    /**
     * Gets location_anatomy
     *
     * @return string
     */
    public function getLocationAnatomy()
    {
        return $this->container['location_anatomy'];
    }

    /**
     * Sets location_anatomy
     *
     * @param string $location_anatomy location_anatomy
     *
     * @return $this
     */
    public function setLocationAnatomy($location_anatomy)
    {
        $this->container['location_anatomy'] = $location_anatomy;

        return $this;
    }

    /**
     * Gets confirm_id
     *
     * @return string
     */
    public function getConfirmId()
    {
        return $this->container['confirm_id'];
    }

    /**
     * Sets confirm_id
     *
     * @param string $confirm_id confirm_id
     *
     * @return $this
     */
    public function setConfirmId($confirm_id)
    {
        $this->container['confirm_id'] = $confirm_id;

        return $this;
    }

    /**
     * Gets lab_id
     *
     * @return string
     */
    public function getLabId()
    {
        return $this->container['lab_id'];
    }

    /**
     * Sets lab_id
     *
     * @param string $lab_id lab_id
     *
     * @return $this
     */
    public function setLabId($lab_id)
    {
        $this->container['lab_id'] = $lab_id;

        return $this;
    }

    /**
     * Gets specimen_id
     *
     * @return string
     */
    public function getSpecimenId()
    {
        return $this->container['specimen_id'];
    }

    /**
     * Sets specimen_id
     *
     * @param string $specimen_id specimen_id
     *
     * @return $this
     */
    public function setSpecimenId($specimen_id)
    {
        $this->container['specimen_id'] = $specimen_id;

        return $this;
    }

    /**
     * Gets no_sediaan
     *
     * @return string
     */
    public function getNoSediaan()
    {
        return $this->container['no_sediaan'];
    }

    /**
     * Sets no_sediaan
     *
     * @param string $no_sediaan no_sediaan
     *
     * @return $this
     */
    public function setNoSediaan($no_sediaan)
    {
        $this->container['no_sediaan'] = $no_sediaan;

        return $this;
    }

    /**
     * Gets no_urut
     *
     * @return string
     */
    public function getNoUrut()
    {
        return $this->container['no_urut'];
    }

    /**
     * Sets no_urut
     *
     * @param string $no_urut no_urut
     *
     * @return $this
     */
    public function setNoUrut($no_urut)
    {
        $this->container['no_urut'] = $no_urut;

        return $this;
    }

    /**
     * Gets error
     *
     * @return string
     */
    public function getError()
    {
        return $this->container['error'];
    }

    /**
     * Sets error
     *
     * @param string $error error
     *
     * @return $this
     */
    public function setError($error)
    {
        $this->container['error'] = $error;

        return $this;
    }

    /**
     * Gets success
     *
     * @return bool
     */
    public function getSuccess()
    {
        return $this->container['success'];
    }

    /**
     * Sets success
     *
     * @param bool $success success
     *
     * @return $this
     */
    public function setSuccess($success)
    {
        $this->container['success'] = $success;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
