<?php
/**
 * ServiceRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Mediator\SatuSehat\Lib\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Swagger Mediator  SATUSEHAT
 *
 * Spesifikasi API ini merupakan contoh untuk menggunakan **Mediator Interoperabilitas SATUSEHAT** yang secara khusus ditujukan untuk mempercepat dan memudahkan proses interoperabilitas data Rekam Medis Elektronik (RME) antara sistem informasi di Fasilitas Kesehatan (Rumah Sakit, Puskesmas, Klinik, Laboratorium, dll) dengan Platform SATUSEHAT.  Mediator Interoperabilitas SATUSEHAT menyediakan format custom yang disederhanakan dari format HL7 FHIR sebagai perantara antara sistem RME dengan SATUSEHAT beserta sistem informasi kesehatan yang ada ditingkat nasional.
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.59
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Mediator\SatuSehat\Lib\Client;

use PHPUnit\Framework\TestCase;

/**
 * ServiceRequestTest Class Doc Comment
 *
 * @category    Class
 * @description ServiceRequest
 * @package     Mediator\SatuSehat\Lib\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ServiceRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ServiceRequest"
     */
    public function testServiceRequest()
    {
    }

    /**
     * Test attribute "referral_no"
     */
    public function testPropertyReferralNo()
    {
    }

    /**
     * Test attribute "code_request"
     */
    public function testPropertyCodeRequest()
    {
    }

    /**
     * Test attribute "faskes_tujuan"
     */
    public function testPropertyFaskesTujuan()
    {
    }

    /**
     * Test attribute "referral_status"
     */
    public function testPropertyReferralStatus()
    {
    }

    /**
     * Test attribute "location_code"
     */
    public function testPropertyLocationCode()
    {
    }

    /**
     * Test attribute "requested_time"
     */
    public function testPropertyRequestedTime()
    {
    }

    /**
     * Test attribute "requester_type"
     */
    public function testPropertyRequesterType()
    {
    }

    /**
     * Test attribute "requester"
     */
    public function testPropertyRequester()
    {
    }

    /**
     * Test attribute "reason_code"
     */
    public function testPropertyReasonCode()
    {
    }

    /**
     * Test attribute "reason_detail"
     */
    public function testPropertyReasonDetail()
    {
    }

    /**
     * Test attribute "occurrence_time"
     */
    public function testPropertyOccurrenceTime()
    {
    }

    /**
     * Test attribute "reason_observation"
     */
    public function testPropertyReasonObservation()
    {
    }
}
