<?php
/**
 * SubmitRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Mediator\SatuSehat\Lib\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Swagger Mediator  SATUSEHAT
 *
 * Spesifikasi API ini merupakan contoh untuk menggunakan **Mediator Interoperabilitas SATUSEHAT** yang secara khusus ditujukan untuk mempercepat dan memudahkan proses interoperabilitas data Rekam Medis Elektronik (RME) antara sistem informasi di Fasilitas Kesehatan (Rumah Sakit, Puskesmas, Klinik, Laboratorium, dll) dengan Platform SATUSEHAT.  Mediator Interoperabilitas SATUSEHAT menyediakan format custom yang disederhanakan dari format HL7 FHIR sebagai perantara antara sistem RME dengan SATUSEHAT beserta sistem informasi kesehatan yang ada ditingkat nasional.
 *
 * OpenAPI spec version: 1.0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.59
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Mediator\SatuSehat\Lib\Client;

use PHPUnit\Framework\TestCase;

/**
 * SubmitRequestTest Class Doc Comment
 *
 * @category    Class
 * @description SubmitRequest
 * @package     Mediator\SatuSehat\Lib\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SubmitRequestTest extends TestCase
{
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SubmitRequest"
     */
    public function testSubmitRequest()
    {
    }

    /**
     * Test attribute "profile"
     */
    public function testPropertyProfile()
    {
    }

    /**
     * Test attribute "organization_id"
     */
    public function testPropertyOrganizationId()
    {
    }

    /**
     * Test attribute "location_id"
     */
    public function testPropertyLocationId()
    {
    }

    /**
     * Test attribute "practitioner_nik"
     */
    public function testPropertyPractitionerNik()
    {
    }

    /**
     * Test attribute "patient"
     */
    public function testPropertyPatient()
    {
    }

    /**
     * Test attribute "tb_suspect"
     */
    public function testPropertyTbSuspect()
    {
    }

    /**
     * Test attribute "tb_confirm"
     */
    public function testPropertyTbConfirm()
    {
    }

    /**
     * Test attribute "encounter"
     */
    public function testPropertyEncounter()
    {
    }

    /**
     * Test attribute "condition"
     */
    public function testPropertyCondition()
    {
    }

    /**
     * Test attribute "observation"
     */
    public function testPropertyObservation()
    {
    }

    /**
     * Test attribute "procedure"
     */
    public function testPropertyProcedure()
    {
    }

    /**
     * Test attribute "specimen"
     */
    public function testPropertySpecimen()
    {
    }

    /**
     * Test attribute "diagnostic_report"
     */
    public function testPropertyDiagnosticReport()
    {
    }

    /**
     * Test attribute "service_request"
     */
    public function testPropertyServiceRequest()
    {
    }

    /**
     * Test attribute "episode_of_care"
     */
    public function testPropertyEpisodeOfCare()
    {
    }

    /**
     * Test attribute "medication"
     */
    public function testPropertyMedication()
    {
    }

    /**
     * Test attribute "medication_statement"
     */
    public function testPropertyMedicationStatement()
    {
    }

    /**
     * Test attribute "immunization"
     */
    public function testPropertyImmunization()
    {
    }

    /**
     * Test attribute "questionnaire_response"
     */
    public function testPropertyQuestionnaireResponse()
    {
    }

    /**
     * Test attribute "composition"
     */
    public function testPropertyComposition()
    {
    }
}
