<?php
/**
 * TbLabRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Swagger Mediator  SATUSEHAT
 *
 * Spesifikasi API ini merupakan contoh untuk menggunakan **Mediator Interoperabilitas SATUSEHAT** yang secara khusus ditujukan untuk mempercepat dan memudahkan proses interoperabilitas data Rekam Medis Elektronik (RME) antara sistem informasi di Fasilitas Kesehatan (Rumah Sakit, Puskesmas, Klinik, Laboratorium, dll) dengan Platform SATUSEHAT.  Mediator Interoperabilitas SATUSEHAT menyediakan format custom yang disederhanakan dari format HL7 FHIR sebagai perantara antara sistem RME dengan SATUSEHAT beserta sistem informasi kesehatan yang ada ditingkat nasional.
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.61
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Mediator\SatuSehat\Lib\Client;

use PHPUnit\Framework\TestCase;

/**
 * TbLabRequestTest Class Doc Comment
 *
 * @category    Class
 * @description TbLabRequest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TbLabRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TbLabRequest"
     */
    public function testTbLabRequest()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "person_id"
     */
    public function testPropertyPersonId()
    {
    }

    /**
     * Test attribute "tgl_daftar"
     */
    public function testPropertyTglDaftar()
    {
    }

    /**
     * Test attribute "dokter_pengirim"
     */
    public function testPropertyDokterPengirim()
    {
    }

    /**
     * Test attribute "tgl_pengambilan"
     */
    public function testPropertyTglPengambilan()
    {
    }

    /**
     * Test attribute "no_sediaan"
     */
    public function testPropertyNoSediaan()
    {
    }

    /**
     * Test attribute "tgl_pengiriman"
     */
    public function testPropertyTglPengiriman()
    {
    }

    /**
     * Test attribute "alasan_pemeriksaan_id"
     */
    public function testPropertyAlasanPemeriksaanId()
    {
    }

    /**
     * Test attribute "follow_up_ke"
     */
    public function testPropertyFollowUpKe()
    {
    }

    /**
     * Test attribute "pemeriksaan_ulang_ke"
     */
    public function testPropertyPemeriksaanUlangKe()
    {
    }

    /**
     * Test attribute "lokasi_penyakit_id"
     */
    public function testPropertyLokasiPenyakitId()
    {
    }

    /**
     * Test attribute "periksa_mikroskopis_id"
     */
    public function testPropertyPeriksaMikroskopisId()
    {
    }

    /**
     * Test attribute "periksa_xpert_id"
     */
    public function testPropertyPeriksaXpertId()
    {
    }

    /**
     * Test attribute "contoh_uji_id"
     */
    public function testPropertyContohUjiId()
    {
    }

    /**
     * Test attribute "contoh_uji_lain"
     */
    public function testPropertyContohUjiLain()
    {
    }

    /**
     * Test attribute "waktu1_id"
     */
    public function testPropertyWaktu1Id()
    {
    }

    /**
     * Test attribute "lab_provinsi_id"
     */
    public function testPropertyLabProvinsiId()
    {
    }

    /**
     * Test attribute "lab_kabupaten_id"
     */
    public function testPropertyLabKabupatenId()
    {
    }

    /**
     * Test attribute "lab_tujuan_id"
     */
    public function testPropertyLabTujuanId()
    {
    }
}
