<?php
/**
 * TbSuspectTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Mediator\SatuSehat\Lib\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Swagger Mediator  SATUSEHAT
 *
 * Spesifikasi API ini merupakan contoh untuk menggunakan **Mediator Interoperabilitas SATUSEHAT** yang secara khusus ditujukan untuk mempercepat dan memudahkan proses interoperabilitas data Rekam Medis Elektronik (RME) antara sistem informasi di Fasilitas Kesehatan (Rumah Sakit, Puskesmas, Klinik, Laboratorium, dll) dengan Platform SATUSEHAT.  Mediator Interoperabilitas SATUSEHAT menyediakan format custom yang disederhanakan dari format HL7 FHIR sebagai perantara antara sistem RME dengan SATUSEHAT beserta sistem informasi kesehatan yang ada ditingkat nasional.
 *
 * OpenAPI spec version: 1.0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.59
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Mediator\SatuSehat\Lib\Client;

use PHPUnit\Framework\TestCase;

/**
 * TbSuspectTest Class Doc Comment
 *
 * @category    Class
 * @description TbSuspect
 * @package     Mediator\SatuSehat\Lib\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TbSuspectTest extends TestCase
{
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TbSuspect"
     */
    public function testTbSuspect()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "person_id"
     */
    public function testPropertyPersonId()
    {
    }

    /**
     * Test attribute "tgl_daftar"
     */
    public function testPropertyTglDaftar()
    {
    }

    /**
     * Test attribute "fasyankes_id"
     */
    public function testPropertyFasyankesId()
    {
    }

    /**
     * Test attribute "jenis_fasyankes_id"
     */
    public function testPropertyJenisFasyankesId()
    {
    }

    /**
     * Test attribute "fasyankes_provinsi_id"
     */
    public function testPropertyFasyankesProvinsiId()
    {
    }

    /**
     * Test attribute "fasyankes_kabupaten_id"
     */
    public function testPropertyFasyankesKabupatenId()
    {
    }

    /**
     * Test attribute "umur"
     */
    public function testPropertyUmur()
    {
    }

    /**
     * Test attribute "umur_bl"
     */
    public function testPropertyUmurBl()
    {
    }

    /**
     * Test attribute "fasyankes_rujukan_id"
     */
    public function testPropertyFasyankesRujukanId()
    {
    }

    /**
     * Test attribute "jenis_fasyankes_rujukan_id"
     */
    public function testPropertyJenisFasyankesRujukanId()
    {
    }

    /**
     * Test attribute "fasyankes_rujukan_lain"
     */
    public function testPropertyFasyankesRujukanLain()
    {
    }

    /**
     * Test attribute "provinsi_rujukan_id"
     */
    public function testPropertyProvinsiRujukanId()
    {
    }

    /**
     * Test attribute "kabupaten_rujukan_id"
     */
    public function testPropertyKabupatenRujukanId()
    {
    }

    /**
     * Test attribute "asal_rujukan_id"
     */
    public function testPropertyAsalRujukanId()
    {
    }

    /**
     * Test attribute "asal_rujukan_lain"
     */
    public function testPropertyAsalRujukanLain()
    {
    }

    /**
     * Test attribute "fasyankes_rujukan_asal_id"
     */
    public function testPropertyFasyankesRujukanAsalId()
    {
    }

    /**
     * Test attribute "terduga_tb_id"
     */
    public function testPropertyTerdugaTbId()
    {
    }

    /**
     * Test attribute "terduga_ro_id"
     */
    public function testPropertyTerdugaRoId()
    {
    }

    /**
     * Test attribute "tipe_pasien_id"
     */
    public function testPropertyTipePasienId()
    {
    }

    /**
     * Test attribute "skoring_tbc_anak"
     */
    public function testPropertySkoringTbcAnak()
    {
    }

    /**
     * Test attribute "status_dm_id"
     */
    public function testPropertyStatusDmId()
    {
    }

    /**
     * Test attribute "status_hiv_id"
     */
    public function testPropertyStatusHivId()
    {
    }

    /**
     * Test attribute "imunisasi_bcg_id"
     */
    public function testPropertyImunisasiBcgId()
    {
    }

    /**
     * Test attribute "no_reg_fasyankes"
     */
    public function testPropertyNoRegFasyankes()
    {
    }

    /**
     * Test attribute "reg_kab_id"
     */
    public function testPropertyRegKabId()
    {
    }

    /**
     * Test attribute "no_reg_kab"
     */
    public function testPropertyNoRegKab()
    {
    }

    /**
     * Test attribute "location_anatomy"
     */
    public function testPropertyLocationAnatomy()
    {
    }

    /**
     * Test attribute "confirm_id"
     */
    public function testPropertyConfirmId()
    {
    }

    /**
     * Test attribute "lab_id"
     */
    public function testPropertyLabId()
    {
    }

    /**
     * Test attribute "specimen_id"
     */
    public function testPropertySpecimenId()
    {
    }

    /**
     * Test attribute "no_sediaan"
     */
    public function testPropertyNoSediaan()
    {
    }

    /**
     * Test attribute "no_urut"
     */
    public function testPropertyNoUrut()
    {
    }
}
